CREATE TABLE IF NOT EXISTS lahan (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  nama_lahan VARCHAR(120) NOT NULL,
  kode_lahan VARCHAR(50) NULL,
  luas DECIMAL(12,2) NULL COMMENT 'Luas input manual dalam hektar',
  tanaman_id INT UNSIGNED NULL,
  komoditas VARCHAR(120) NULL,
  lokasi VARCHAR(190) NULL,
  status ENUM('persiapan', 'aktif', 'menjelang_panen', 'inspeksi', 'selesai') NOT NULL DEFAULT 'aktif',
  latitude DECIMAL(10,8) NULL,
  longitude DECIMAL(11,8) NULL,
  polygon_area JSON NULL,
  luas_lahan DECIMAL(14,2) NULL COMMENT 'Luas hasil hitung polygon dalam meter persegi',
  deleted_at DATETIME NULL,
  catatan TEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lahan_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_lahan_tanaman FOREIGN KEY (tanaman_id) REFERENCES tanaman(id) ON DELETE SET NULL,
  UNIQUE KEY uq_lahan_user_nama (user_id, nama_lahan),
  INDEX idx_lahan_user_status (user_id, status),
  INDEX idx_lahan_deleted_at (deleted_at),
  INDEX idx_lahan_deleted_updated (deleted_at, updated_at),
  INDEX idx_lahan_komoditas (komoditas)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
