CREATE TABLE IF NOT EXISTS musim_tanam (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  lahan_id INT UNSIGNED NOT NULL,
  tanaman_id INT UNSIGNED NULL,
  kode_musim VARCHAR(30) NOT NULL,
  nama_musim VARCHAR(120) NULL,
  tanggal_tanam DATE NOT NULL,
  estimasi_panen DATE NULL,
  tanggal_panen DATE NULL,
  fase ENUM('persiapan', 'vegetatif', 'generatif', 'generatif_akhir', 'panen', 'selesai', 'gagal') NOT NULL DEFAULT 'persiapan',
  progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('aktif', 'selesai', 'dibatalkan') NOT NULL DEFAULT 'aktif',
  catatan TEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_musim_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_musim_lahan FOREIGN KEY (lahan_id) REFERENCES lahan(id) ON DELETE CASCADE,
  CONSTRAINT fk_musim_tanaman FOREIGN KEY (tanaman_id) REFERENCES tanaman(id) ON DELETE SET NULL,
  UNIQUE KEY uq_musim_lahan_kode (lahan_id, kode_musim),
  INDEX idx_musim_user_status (user_id, status),
  INDEX idx_musim_lahan (lahan_id),
  INDEX idx_musim_user_tanggal (user_id, tanggal_tanam),
  INDEX idx_musim_tanggal (tanggal_tanam)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
