CREATE TABLE IF NOT EXISTS katalog_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kode VARCHAR(80) NOT NULL UNIQUE,
  kategori VARCHAR(80) NOT NULL,
  subkategori VARCHAR(120) NULL,
  nama VARCHAR(160) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  image_path VARCHAR(255) NULL,
  komoditas VARCHAR(120) NOT NULL DEFAULT 'padi,jagung,kedelai',
  fase VARCHAR(120) NOT NULL,
  jenis_biaya VARCHAR(80) NOT NULL,
  mode_biaya VARCHAR(80) NOT NULL DEFAULT 'input_manual',
  satuan_default VARCHAR(40) NULL,
  harga_min DECIMAL(14,2) NULL,
  harga_max DECIMAL(14,2) NULL,
  harga_status VARCHAR(80) NOT NULL DEFAULT 'INPUT_MANUAL',
  sumber_referensi TEXT NULL,
  sumber_dokumen VARCHAR(190) NULL,
  tanggal_cek_harga DATE NULL,
  fungsi TEXT NULL,
  keterangan TEXT NULL,
  risiko TEXT NULL,
  admin_note TEXT NULL,
  detail_json JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_katalog_filter (kategori, fase, is_active),
  INDEX idx_katalog_komoditas (komoditas),
  INDEX idx_katalog_active_nama (is_active, nama)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
