CREATE TABLE IF NOT EXISTS biaya_operasional (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  lahan_id INT UNSIGNED NOT NULL,
  musim_tanam_id INT UNSIGNED NOT NULL,
  katalog_item_id INT UNSIGNED NULL,
  tanggal DATE NOT NULL,
  kategori VARCHAR(80) NOT NULL,
  subkategori VARCHAR(120) NULL,
  nama_item VARCHAR(160) NOT NULL,
  mode_biaya VARCHAR(80) NOT NULL DEFAULT 'input_manual',
  jumlah DECIMAL(14,2) NOT NULL DEFAULT 1,
  satuan VARCHAR(40) NOT NULL DEFAULT 'unit',
  harga_satuan DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_biaya DECIMAL(14,2) NOT NULL DEFAULT 0,
  catatan TEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_biaya_ops_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_biaya_ops_lahan FOREIGN KEY (lahan_id) REFERENCES lahan(id) ON DELETE CASCADE,
  CONSTRAINT fk_biaya_ops_musim FOREIGN KEY (musim_tanam_id) REFERENCES musim_tanam(id) ON DELETE CASCADE,
  CONSTRAINT fk_biaya_ops_katalog FOREIGN KEY (katalog_item_id) REFERENCES katalog_items(id) ON DELETE SET NULL,
  INDEX idx_biaya_ops_user_tanggal (user_id, tanggal),
  INDEX idx_biaya_ops_musim (musim_tanam_id),
  INDEX idx_biaya_ops_kategori (kategori),
  INDEX idx_biaya_ops_user_kategori (user_id, kategori),
  INDEX idx_biaya_ops_tanggal (tanggal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
