<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/core/bootstrap.php'; require_once __DIR__ . '/../../app/core/layout.php'; require_once __DIR__ . '/../../app/core/queries.php';
$user=require_login('admin'); $summary=admin_summary();
$users=db()->query('SELECT id,name,email,role,status,created_at FROM users ORDER BY id')->fetchAll();
$lahan=db()->query('SELECT l.*, u.name petani FROM lahan l JOIN users u ON u.id=l.user_id ORDER BY l.id')->fetchAll();
$musim=db()->query('SELECT mt.*, u.name petani, l.nama_lahan, t.nama tanaman FROM musim_tanam mt JOIN users u ON u.id=mt.user_id JOIN lahan l ON l.id=mt.lahan_id LEFT JOIN tanaman t ON t.id=mt.tanaman_id ORDER BY mt.tanggal_tanam DESC')->fetchAll();
?>
<!doctype html><html lang="id"><head><?php render_head('AgroTrack - Laporan Admin'); ?></head><body data-portal="admin" data-active="laporan" data-base="../../"><?php render_sidebar($user,'laporan');?><main class="app-main"><div class="topbar"><div><h1 class="page-title">Laporan Global</h1><p class="page-kicker">Seluruh data utama AgroTrack dari database.</p></div><button class="btn btn-primary" id="exportPdfBtn" type="button">Generate PDF</button></div>
<section class="row g-3 mb-3"><div class="col-md-3"><div class="stat-card"><div class="stat-label">User</div><div class="stat-value"><?=e($summary['total_users'])?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-label">Luas</div><div class="stat-value"><?=number_id($summary['total_luas_ha'],1)?> Ha</div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-label">Pendapatan</div><div class="stat-value"><?=money_id($summary['total_pendapatan'])?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-label">Profit</div><div class="stat-value"><?=money_id($summary['total_profit'])?></div></div></div></section>
<section class="panel report-section"><h2>Data Pengguna</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody><?php foreach($users as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['email'])?></td><td><?=e($r['role'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel report-section"><h2>Data Lahan</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Petani</th><th>Lahan</th><th>Komoditas</th><th>Luas</th><th>Status</th></tr></thead><tbody><?php foreach($lahan as $r):?><tr><td><?=e($r['petani'])?></td><td><?=e($r['nama_lahan'])?></td><td><?=e($r['komoditas'])?></td><td><?=number_id($r['luas'],2)?> Ha</td><td><?=e($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel report-section"><h2>Musim Tanam</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Petani</th><th>Musim</th><th>Lahan</th><th>Tanaman</th><th>Tanam</th><th>Estimasi</th></tr></thead><tbody><?php foreach($musim as $r):?><tr><td><?=e($r['petani'])?></td><td><?=e($r['kode_musim'])?></td><td><?=e($r['nama_lahan'])?></td><td><?=e($r['tanaman'])?></td><td><?=e($r['tanggal_tanam'])?></td><td><?=e($r['estimasi_panen'])?></td></tr><?php endforeach;?></tbody></table></div></section>
</main><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js"></script><script src="../../assets/js/laporan-admin.js"></script><script src="../../assets/js/app.js"></script></body></html>
