<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/core/bootstrap.php'; require_once __DIR__ . '/../../app/core/layout.php'; require_once __DIR__ . '/../../app/core/queries.php';
$user=require_login('admin'); $summary=admin_summary();
$users=db()->query('SELECT id,name,email,role,status,created_at FROM users ORDER BY id')->fetchAll();
$lahan=db()->query('SELECT l.*, u.name petani FROM lahan l JOIN users u ON u.id=l.user_id ORDER BY l.id')->fetchAll();
$musim=db()->query('SELECT mt.*, u.name petani, l.nama_lahan, t.nama tanaman FROM musim_tanam mt JOIN users u ON u.id=mt.user_id JOIN lahan l ON l.id=mt.lahan_id LEFT JOIN tanaman t ON t.id=mt.tanaman_id ORDER BY mt.tanggal_tanam DESC')->fetchAll();
$biaya=db()->query('SELECT bo.*, u.name petani, mt.kode_musim FROM biaya_operasional bo JOIN users u ON u.id=bo.user_id LEFT JOIN musim_tanam mt ON mt.id=bo.musim_tanam_id ORDER BY bo.tanggal DESC LIMIT 250')->fetchAll();
$katalog=db()->query('SELECT kategori, COUNT(*) total_item, SUM(is_active=1) aktif FROM katalog_items GROUP BY kategori ORDER BY kategori')->fetchAll();
?>
<!doctype html><html lang="id"><head><?php render_head('AgroTrack - Laporan Admin'); ?></head><body data-portal="admin" data-active="laporan" data-base="../../"><?php render_sidebar($user,'laporan');?><main class="app-main"><div class="topbar"><div><h1 class="page-title">Laporan Global</h1><p class="page-kicker">Seluruh data utama AgroTrack dari database.</p></div><button class="btn btn-primary" id="exportPdfBtn" type="button"><span class="material-symbols-outlined">picture_as_pdf</span> Generate PDF</button></div><?php render_page_help('Cara memakai laporan', ['Cek ringkasan angka di bagian atas terlebih dahulu.', 'Scroll tabel untuk melihat pengguna, lahan, musim tanam, katalog, dan biaya.', 'Klik Generate PDF untuk membuat file laporan dari data yang sedang tampil.'], 'Laporan bersifat global dan menggabungkan data seluruh petani.', 'dashboard.php', 'Kembali Dashboard'); ?>
<section class="row g-3 mb-3"><div class="col-md-3"><div class="stat-card"><div class="stat-label">User</div><div class="stat-value"><?=e($summary['total_users'])?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-label">Luas</div><div class="stat-value"><?=number_id($summary['total_luas_ha'],1)?> Ha</div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-label">Pendapatan</div><div class="stat-value"><?=money_id($summary['total_pendapatan'])?></div></div></div><div class="col-md-3"><div class="stat-card"><div class="stat-label">Profit</div><div class="stat-value"><?=money_id($summary['total_profit'])?></div></div></div></section>
<section class="panel report-section"><h2>Data Pengguna</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody><?php foreach($users as $r):?><tr><td><?=e($r['name'])?></td><td><?=e($r['email'])?></td><td><?=e($r['role'])?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel report-section"><h2>Data Lahan</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Petani</th><th>Lahan</th><th>Komoditas</th><th>Luas Polygon</th><th>Status</th></tr></thead><tbody><?php foreach($lahan as $r):?><tr><td><?=e($r['petani'])?></td><td><?=e($r['nama_lahan'])?></td><td><?=e($r['komoditas'])?></td><td><?= $r['luas_lahan'] ? number_id($r['luas_lahan']/10000,4).' Ha' : 'Belum digambar' ?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel report-section"><h2>Musim Tanam</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Petani</th><th>Musim</th><th>Lahan</th><th>Tanaman</th><th>Tanam</th><th>Estimasi</th></tr></thead><tbody><?php foreach($musim as $r):?><tr><td><?=e($r['petani'])?></td><td><?=e($r['kode_musim'])?></td><td><?=e($r['nama_lahan'])?></td><td><?=e($r['tanaman'])?></td><td><?=e($r['tanggal_tanam'])?></td><td><?=e($r['estimasi_panen'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel report-section"><h2>Katalog Kebutuhan</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Kategori</th><th>Total Item</th><th>Aktif</th></tr></thead><tbody><?php foreach($katalog as $r):?><tr><td><?=e($r['kategori'])?></td><td><?=e($r['total_item'])?></td><td><?=e($r['aktif'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel report-section"><h2>Biaya Operasional</h2><div class="table-responsive"><table class="table admin-table"><thead><tr><th>Tanggal</th><th>Petani</th><th>Musim</th><th>Kategori</th><th>Item</th><th>Total</th></tr></thead><tbody><?php foreach($biaya as $r):?><tr><td><?=e($r['tanggal'])?></td><td><?=e($r['petani'])?></td><td><?=e($r['kode_musim'])?></td><td><?=e($r['kategori'])?></td><td><?=e($r['nama_item'])?></td><td><?=money_id($r['total_biaya'])?></td></tr><?php endforeach;?></tbody></table></div></section>
</main><script src="https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js"></script><script src="https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js"></script><script src="../../assets/js/laporan-admin.js"></script><script src="../../assets/js/app.js"></script></body></html>
