USE agrotrack;

INSERT INTO users (name, email, phone, profile_photo, address, division, main_crop, total_area, role, status, password_hash)
VALUES
('Admin Root', 'admin@agrotrack.com', '081298765432', 'assets/image/profil/foto_profil_6.jpg', 'Surabaya, Jawa Timur', 'Operasional Platform', NULL, NULL, 'admin', 'aktif', '$2y$10$uK9.ecR/LaItdL1tducqQuShNJISZ4zpIOBnoUQYOrUpXWtsNZdiu'),
('Petani Demo', 'petani@agrotrack.test', '081234567890', 'assets/image/profil/farmer-profile.jpg', 'Sidoarjo, Jawa Timur', 'Kelompok Tani Digital', 'Padi', 12.80, 'petani', 'aktif', '$2y$10$CrF7Q9zPPMC0ZETq2LnBEukujmJcpCrDV.wiBrktaqOACtzlnQVa2')
ON DUPLICATE KEY UPDATE name=VALUES(name), password_hash=VALUES(password_hash), status='aktif';

INSERT INTO tanaman (nama, slug, kategori, masa_panen_hari, deskripsi, gambar_url, status) VALUES
('Padi Ciherang', 'padi-ciherang', 'Padi', 110, 'Padi sawah produktif untuk musim hujan.', 'assets/image/gambar_tanaman/gambar_padi_1.jpg', 'aktif'),
('Jagung Hibrida', 'jagung-hibrida', 'Jagung', 100, 'Jagung hibrida untuk lahan kering.', 'assets/image/gambar_tanaman/gambar_jagung_1.jpg', 'aktif'),
('Kedelai Anjasmoro', 'kedelai-anjasmoro', 'Kedelai', 85, 'Kedelai rotasi dengan masa panen cepat.', 'assets/image/gambar_tanaman/gambar_kedelai_1.jpg', 'aktif')
ON DUPLICATE KEY UPDATE masa_panen_hari=VALUES(masa_panen_hari), status='aktif';

SET @petani_id := (SELECT id FROM users WHERE email='petani@agrotrack.test');
SET @padi_id := (SELECT id FROM tanaman WHERE slug='padi-ciherang');
SET @jagung_id := (SELECT id FROM tanaman WHERE slug='jagung-hibrida');

INSERT INTO lahan (user_id, nama_lahan, kode_lahan, luas, tanaman_id, komoditas, lokasi, status, latitude, longitude, polygon_area, luas_lahan)
VALUES
(@petani_id, 'Sawah B-12', 'B-12', 4.20, @padi_id, 'Padi Ciherang', 'Sidoarjo, Jawa Timur', 'aktif', -7.44700000, 112.71800000, JSON_OBJECT('type','Polygon','coordinates',JSON_ARRAY(JSON_ARRAY(JSON_ARRAY(112.716,-7.446),JSON_ARRAY(112.720,-7.446),JSON_ARRAY(112.720,-7.449),JSON_ARRAY(112.716,-7.449),JSON_ARRAY(112.716,-7.446)))), 147000.00),
(@petani_id, 'Blok A-03', 'A-03', 2.80, @jagung_id, 'Jagung Hibrida', 'Mojokerto, Jawa Timur', 'persiapan', NULL, NULL, NULL, NULL)
ON DUPLICATE KEY UPDATE luas=VALUES(luas), tanaman_id=VALUES(tanaman_id), komoditas=VALUES(komoditas);

SET @lahan_padi := (SELECT id FROM lahan WHERE user_id=@petani_id AND nama_lahan='Sawah B-12');
SET @lahan_jagung := (SELECT id FROM lahan WHERE user_id=@petani_id AND nama_lahan='Blok A-03');

INSERT INTO musim_tanam (user_id, lahan_id, tanaman_id, kode_musim, nama_musim, tanggal_tanam, estimasi_panen, fase, progress, status)
VALUES
(@petani_id, @lahan_padi, @padi_id, 'MT-2026-PADI', 'Musim Padi 2026', '2026-03-10', DATE_ADD('2026-03-10', INTERVAL 110 DAY), 'generatif', 70, 'aktif'),
(@petani_id, @lahan_jagung, @jagung_id, 'MT-2026-JAGUNG', 'Musim Jagung 2026', '2026-04-22', DATE_ADD('2026-04-22', INTERVAL 100 DAY), 'vegetatif', 45, 'aktif')
ON DUPLICATE KEY UPDATE estimasi_panen=VALUES(estimasi_panen), tanaman_id=VALUES(tanaman_id);

SET @musim_padi := (SELECT id FROM musim_tanam WHERE kode_musim='MT-2026-PADI');
INSERT INTO biaya_produksi (user_id, lahan_id, musim_tanam_id, tanggal, kategori, deskripsi, jumlah, satuan, harga_satuan, total_biaya)
VALUES
(@petani_id, @lahan_padi, @musim_padi, '2026-03-12', 'benih', 'Bibit Padi Ciherang', 4, 'karung', 125000, 500000),
(@petani_id, @lahan_padi, @musim_padi, '2026-04-01', 'pupuk', 'Pupuk Phonska', 6, 'sak', 175000, 1050000),
(@petani_id, @lahan_padi, @musim_padi, '2026-04-15', 'tenaga_kerja', 'Tenaga pemupukan', 1, 'paket', 1500000, 1500000);

INSERT INTO hasil_panen (user_id, lahan_id, musim_tanam_id, tanggal_panen, komoditas, berat_kg, harga_per_kg, total_pendapatan, kualitas, status, pembeli)
VALUES (@petani_id, @lahan_padi, @musim_padi, '2026-06-28', 'Padi Ciherang', 7200, 6200, 44640000, 'baik', 'terverifikasi', 'Koperasi Tani')
ON DUPLICATE KEY UPDATE total_pendapatan=VALUES(total_pendapatan);

INSERT INTO katalog_items
(kode, kategori, subkategori, nama, slug, image_path, komoditas, fase, jenis_biaya, mode_biaya, satuan_default, harga_min, harga_max, harga_status, sumber_referensi, sumber_dokumen, tanggal_cek_harga, fungsi, keterangan, risiko, admin_note)
VALUES
('BEN-PADI-CIHERANG','Benih & Bibit','Padi','Benih Padi Ciherang','benih-padi-ciherang','assets/image/bibit/padi-ciherang.jpg','padi','Pra-tanam / Tanam','saprodi','jumlah_x_harga','kg',21600,23840,'TERVERIFIKASI_MARKETPLACE','Shopee/Lazada 5 kg, harga per kg dihitung dari dokumen katalog.','AGROTRACK_KATALOG_BENIH_BIBIT_REVISI_BERBASIS_SUMBER.md','2026-06-16','Benih utama untuk budidaya padi sawah.','Harga referensi katalog, admin tetap bisa edit sesuai toko lokal.','Harga berubah karena stok, wilayah, ongkir, diskon, dan kelas benih.','Gunakan untuk opsi awal biaya benih padi.'),
('BEN-PADI-INPARI32','Benih & Bibit','Padi','Benih Padi Inpari 32 HDB','benih-padi-inpari-32','assets/image/bibit/padi-inpari-32.jpg','padi','Pra-tanam / Tanam','saprodi','jumlah_x_harga','kg',17000,28000,'TERVERIFIKASI_MARKETPLACE','Purotani dan Shopee list Inpari 32.','AGROTRACK_KATALOG_BENIH_BIBIT_REVISI_BERBASIS_SUMBER.md','2026-06-16','Opsi benih padi inbrida untuk sawah.','Simpan sebagai referensi, bukan janji hasil.','Ketahanan dan hasil dipengaruhi kondisi lahan dan musim.',''),
('BEN-JAGUNG-NASA29','Benih & Bibit','Jagung','Benih Jagung Hibrida NASA 29','benih-jagung-nasa-29','assets/image/bibit/jagung-nasa-29.jpg','jagung','Pra-tanam / Tanam','saprodi','jumlah_x_harga','kg',20000,35000,'TERVERIFIKASI_BERBEDA_SUMBER','Shopee/BigGo dan kajian VUB jagung hibrida.','AGROTRACK_KATALOG_BENIH_BIBIT_REVISI_BERBASIS_SUMBER.md','2026-06-16','Benih jagung hibrida untuk musim tanam jagung.','Rentang sumber berbeda, tampilkan sebagai referensi.','Harga hibrida sangat tergantung merek dan kemasan.',''),
('BEN-JAGUNG-JH45','Benih & Bibit','Jagung','Benih Jagung Hibrida JH 45','benih-jagung-jh-45','assets/image/bibit/jagung-jh-45.jpg','jagung','Pra-tanam / Tanam','saprodi','input_manual','kg',NULL,NULL,'BELUM_TERVERIFIKASI','Dokumen menyebut harga spesifik belum ditemukan jelas.','AGROTRACK_KATALOG_BENIH_BIBIT_REVISI_BERBASIS_SUMBER.md','2026-06-16','Opsi katalog benih jagung, perlu harga dari admin.','Harga wajib diisi manual sebelum dipakai sebagai biaya.','Jangan mengisi angka karangan.',''),
('BEN-KEDELAI-ANJASMORO','Benih & Bibit','Kedelai','Benih Kedelai Anjasmoro','benih-kedelai-anjasmoro','assets/image/bibit/kedelai-anjasmoro.jpg','kedelai','Pra-tanam / Tanam','saprodi','jumlah_x_harga','kg',20000,38000,'TERVERIFIKASI_MARKETPLACE','Inaproc, Lazada, dan Shopee Anjasmoro.','AGROTRACK_KATALOG_BENIH_BIBIT_REVISI_BERBASIS_SUMBER.md','2026-06-16','Benih kedelai populer untuk musim tanam kedelai.','Harga mengikuti toko dan kelas benih.','Kualitas benih memengaruhi daya tumbuh.',''),
('BEN-KEDELAI-DEGA1','Benih & Bibit','Kedelai','Benih Kedelai Dega 1','benih-kedelai-dega-1','assets/image/bibit/kedelai-dega-1.jpg','kedelai','Pra-tanam / Tanam','saprodi','input_manual','kg',NULL,NULL,'BELUM_TERVERIFIKASI','Sumber spesifikasi tersedia, harga retail spesifik belum jelas.','AGROTRACK_KATALOG_BENIH_BIBIT_REVISI_BERBASIS_SUMBER.md','2026-06-16','Opsi varietas kedelai yang perlu harga lokal.','Admin dapat melengkapi harga setelah cek toko.','Jangan pakai sebagai angka otomatis sebelum diverifikasi.',''),
('PUP-UREA','Pupuk & Nutrisi','Pupuk Makro Tunggal','Pupuk Urea','pupuk-urea','assets/image/pupuk/pupuk-urea.jpg','padi,jagung,kedelai','Vegetatif / Susulan','saprodi','jumlah_x_harga','kg',1800,1800,'HET_SUBSIDI','HET pupuk subsidi 2025 dari Pupuk Indonesia.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Sumber nitrogen utama untuk pertumbuhan daun dan batang.','Gunakan sesuai rekomendasi setempat.','Pemakaian berlebih dapat tidak efisien dan meningkatkan risiko rebah.',''),
('PUP-NPK-PHONSKA','Pupuk & Nutrisi','Pupuk Majemuk NPK','Pupuk NPK Phonska','pupuk-npk-phonska','assets/image/pupuk/pupuk-npk-phonska.jpg','padi,jagung,kedelai','Dasar / Susulan','saprodi','jumlah_x_harga','kg',1840,1840,'HET_SUBSIDI','HET pupuk subsidi 2025 dari Pupuk Indonesia.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Pupuk majemuk NPK untuk hara utama.','Cocok sebagai item default biaya pupuk.','Formula tunggal tidak selalu cocok untuk semua tanah.',''),
('PUP-SP36','Pupuk & Nutrisi','Pupuk Fosfat','Pupuk SP-36','pupuk-sp36','assets/image/pupuk/pupuk-sp36.jpg','padi,jagung,kedelai','Pupuk dasar','saprodi','jumlah_x_harga','kg',5995,23240,'REFERENSI_MARKETPLACE','Referensi online non-subsidi per 50 kg dikonversi ke kg.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Sumber fosfat untuk akar dan pembentukan hasil.','Harga non-subsidi bervariasi.','Perlu cek harga kios lokal.',''),
('PUP-KCL-MOP','Pupuk & Nutrisi','Pupuk Kalium','Pupuk KCl / MOP','pupuk-kcl-mop','assets/image/pupuk/pupuk-kcl-mop.jpg','padi,jagung,kedelai','Generatif / Pengisian hasil','saprodi','jumlah_x_harga','kg',9700,16900,'REFERENSI_MARKETPLACE','Referensi marketplace per 50 kg dikonversi ke kg.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Sumber kalium untuk generatif dan kualitas hasil.','Admin dapat ubah harga sesuai distributor.','Harga listing bisa lebih tinggi dari rentang contoh.',''),
('PUP-RHIZOBIUM','Pupuk & Nutrisi','Pupuk Hayati','Pupuk Hayati Rhizobium','pupuk-hayati-rhizobium','assets/image/pembenah_tanaman/pupuk-hayati-rhizobium.jpg','kedelai','Perlakuan benih / Pra-tanam','saprodi','jumlah_x_harga','pack',15000,15000,'REFERENSI_MARKETPLACE','Referensi online Rp15.000/40 g.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Inokulan hayati utama untuk kedelai.','Membantu penambatan nitrogen pada legum.','Efektivitas dipengaruhi kualitas inokulan dan kondisi tanah.',''),
('PEM-KOMPOS','Pembenah Tanah','Organik','Kompos','kompos','assets/image/pembenah_tanaman/pembenah-kompos.jpg','padi,jagung,kedelai','Pra-tanam / Dasar','saprodi','jumlah_x_harga','kg',1332,1332,'REFERENSI_MARKETPLACE','Referensi online Rp66.600/50 kg.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menambah bahan organik dan memperbaiki struktur tanah.','Harga dan kualitas sangat bergantung sumber lokal.','Kematangan kompos perlu dicek.',''),
('PEM-KANDANG','Pembenah Tanah','Organik','Pupuk Kandang','pupuk-kandang','assets/image/pembenah_tanaman/pembenah-pupuk-kandang.jpg','padi,jagung,kedelai','Pra-tanam / Dasar','saprodi','input_manual','kg',NULL,NULL,'PERLU_VERIFIKASI_LOKAL','Dokumen menyebut harga sangat lokal.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Pembenah organik untuk struktur dan aktivitas tanah.','Isi harga dari pemasok lokal.','Kualitas, kadar air, dan kematangan berbeda-beda.',''),
('PEM-DOLOMIT','Pembenah Tanah','Kapur Pertanian','Dolomit / Kapur Pertanian','dolomit-kapur-pertanian','assets/image/pembenah_tanaman/dolomit-kapur-pertanian.jpg','padi,jagung,kedelai','Pra-tanam','saprodi','jumlah_x_harga','kg',666,1650,'REFERENSI_MARKETPLACE','Referensi online per 50 kg dikonversi ke kg.','AGROTRACK_KATALOG_PUPUK_NUTRISI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Membantu memperbaiki tanah masam.','Gunakan jika sesuai kondisi pH tanah.','Aplikasi tanpa cek pH bisa tidak tepat.',''),
('LIN-HERBISIDA','Perlindungan Tanaman','Pestisida Kimia','Herbisida Gulma','herbisida-gulma','assets/image/perlindungan_tanaman/perlintan-herbisida.jpg','padi,jagung,kedelai','Pra-tanam / Awal pertumbuhan / Vegetatif','saprodi','jumlah_x_harga','liter',50000,114400,'TERVERIFIKASI_MARKETPLACE','Shopee dan Lazada contoh produk herbisida 1 liter.','AGROTRACK_KATALOG_PERLINDUNGAN_TANAMAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengendalikan gulma yang bersaing dengan tanaman utama.','Ikuti label produk dan kondisi lapangan.','Salah aplikasi dapat merusak tanaman dan lingkungan.',''),
('LIN-INSEKTISIDA','Perlindungan Tanaman','Pestisida Kimia','Insektisida Hama Serangga','insektisida-hama-serangga','assets/image/perlindungan_tanaman/perlintan-insektisida.jpg','padi,jagung,kedelai','Awal pertumbuhan / Vegetatif / Generatif','saprodi','jumlah_x_harga','produk',24225,195000,'TERVERIFIKASI_MARKETPLACE','Shopee, Lazada, Blibli, dan referensi produk crop protection.','AGROTRACK_KATALOG_PERLINDUNGAN_TANAMAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengendalikan hama serangga berdasarkan monitoring OPT.','Tidak ditampilkan sebagai biaya wajib.','Berisiko bagi musuh alami/operator jika salah pakai.',''),
('LIN-FUNGISIDA','Perlindungan Tanaman','Pestisida Kimia','Fungisida Penyakit Jamur','fungisida-penyakit-jamur','assets/image/perlindungan_tanaman/perlintan-fungisida.jpg','padi,jagung,kedelai','Vegetatif / Generatif','saprodi','jumlah_x_harga','produk',25740,178100,'TERVERIFIKASI_MARKETPLACE','Ringkasan katalog perlindungan tanaman.','AGROTRACK_KATALOG_PERLINDUNGAN_TANAMAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengendalikan penyakit jamur sesuai diagnosis lapang.','Dosis harus mengikuti label produk.','Salah diagnosa membuat biaya tidak efektif.',''),
('LIN-TRICHODERMA','Perlindungan Tanaman','Agens Hayati','Agens Hayati Trichoderma','agens-hayati-trichoderma','assets/image/perlindungan_tanaman/perlintan-trichoderma.jpg','padi,jagung,kedelai','Pra-tanam / Awal pertumbuhan','saprodi','jumlah_x_harga','produk',23750,102500,'TERVERIFIKASI_MARKETPLACE','Ringkasan katalog perlindungan tanaman.','AGROTRACK_KATALOG_PERLINDUNGAN_TANAMAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Agens hayati untuk dukungan pengendalian penyakit tanah.','Simpan sebagai opsi PHT.','Efektivitas dipengaruhi kualitas produk dan aplikasi.',''),
('AIR-POMPA','Air & Irigasi','Peralatan Irigasi','Pompa Air Pertanian / Alkon','pompa-air-pertanian-alkon','assets/image/irigasi/irigasi-pompa-air.jpg','padi,jagung,kedelai','Pra-tanam / Vegetatif / Generatif','aset','beli_sewa_milik_sendiri','unit',1300000,7347750,'TERVERIFIKASI_MARKETPLACE_DAN_JASA','Blibli, Lazada, Shopee, PaDi UMKM, dan jasa sewa.','AGROTRACK_KATALOG_AIR_IRIGASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menyediakan air saat irigasi lahan.','Bisa dicatat sebagai beli, sewa, atau depresiasi.','Biaya musim jangan menggandakan harga aset penuh jika alat milik sendiri.',''),
('AIR-SELANG','Air & Irigasi','Perlengkapan Irigasi','Selang Irigasi / Selang Buang Pompa','selang-irigasi','assets/image/irigasi/irigasi-selang.jpg','padi,jagung,kedelai','Saat irigasi','aset ringan','jumlah_x_harga','roll',65000,765000,'TERVERIFIKASI_MARKETPLACE','Shopee, Lazada, dan Blibli selang irigasi.','AGROTRACK_KATALOG_AIR_IRIGASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menyalurkan air dari pompa ke lahan.','Harga dipengaruhi bahan, tebal, dan panjang.','Pastikan satuan roll/meter tidak tertukar.',''),
('AIR-BBM-POMPA','Air & Irigasi','Bahan Habis Pakai','Bahan Bakar Pompa Air','bahan-bakar-pompa-air','assets/image/irigasi/irigasi-bahan-bakar-pompa.jpg','padi,jagung,kedelai','Setiap penggunaan pompa','operasional','jumlah_x_harga','liter',6800,16250,'HARGA_BBM_DINAMIS','Pertamina Patra Niaga, Reuters, CNN Indonesia.','AGROTRACK_KATALOG_AIR_IRIGASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Biaya operasional pompa berbahan bakar bensin/solar.','Pilih jenis BBM lalu isi liter.','Harga berubah menurut jenis BBM, wilayah, dan periode.',''),
('PRS-BAJAK','Persiapan Lahan','Olah Tanah','Bajak Singkal','bajak-singkal','assets/image/persiapan/persiapan-bajak-singkal.jpg','padi,jagung,kedelai','Pra-tanam','jasa / alat','input_manual','paket',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog persiapan lahan merekomendasikan input lokal.','AGROTRACK_KATALOG_PERSIAPAN_LAHAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Membalik tanah sebelum tanam.','Biaya bergantung luas, alat, dan tenaga lokal.','Jangan gandakan jika sudah masuk paket traktor.',''),
('PRS-ROTAVATOR','Persiapan Lahan','Olah Tanah','Rotavator / Penghalusan Tanah','rotavator-penghalusan-tanah','assets/image/persiapan/persiapan-rotavator.jpg','padi,jagung,kedelai','Pra-tanam','jasa / alat','input_manual','ha',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog persiapan lahan.','AGROTRACK_KATALOG_PERSIAPAN_LAHAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menghaluskan tanah setelah pengolahan awal.','Catat per hektar atau paket.','Periksa apakah sewa alat termasuk operator dan BBM.',''),
('PRS-BEDENGAN','Persiapan Lahan','Bedengan','Pembuatan Bedengan','pembuatan-bedengan','assets/image/persiapan/persiapan-bedengan.jpg','jagung,kedelai','Pra-tanam','tenaga kerja / jasa','input_manual','paket',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog persiapan lahan.','AGROTRACK_KATALOG_PERSIAPAN_LAHAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Membentuk bedengan untuk drainase dan jarak tanam.','Relevan untuk jagung/kedelai pada lahan tertentu.','Ukuran bedengan memengaruhi volume pekerjaan.',''),
('TK-TANAM-PADI','Tenaga Kerja','Tanam','Tenaga Tanam Padi','tenaga-tanam-padi','assets/image/tenaga_kerja/tenaga-tanam-padi.jpg','padi','Tanam','tenaga kerja','input_manual','HOK',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog tenaga kerja menyatakan upah bergantung lokasi.','AGROTRACK_KATALOG_TENAGA_KERJA_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat tenaga kerja saat tanam padi.','Isi upah/HOK atau paket sesuai praktik lokal.','Hindari dobel dengan paket borongan tanam.',''),
('TK-PENYIANGAN','Tenaga Kerja','Pemeliharaan','Tenaga Penyiangan','tenaga-penyiangan','assets/image/tenaga_kerja/tenaga-penyiangan.jpg','padi,jagung,kedelai','Vegetatif','tenaga kerja','input_manual','HOK',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog tenaga kerja.','AGROTRACK_KATALOG_TENAGA_KERJA_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat pekerjaan penyiangan gulma manual.','Bisa dibandingkan dengan biaya herbisida.','Jangan gandakan jika sudah termasuk borongan pemeliharaan.',''),
('TK-PANEN-PADI','Tenaga Kerja','Panen','Tenaga Panen Padi','tenaga-panen-padi','assets/image/tenaga_kerja/tenaga-panen-padi.jpg','padi','Panen','tenaga kerja','input_manual','paket',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog tenaga kerja.','AGROTRACK_KATALOG_TENAGA_KERJA_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat tenaga kerja panen padi manual.','Pisahkan dari biaya combine jika memakai mesin.','Rawan double counting dengan biaya panen mesin.',''),
('ALT-TRAKTOR','Alat & Mesin','Olah Tanah','Traktor Roda Dua','traktor-roda-dua','assets/image/alat_mesin/alat-traktor-roda-dua.jpg','padi,jagung,kedelai','Pra-tanam','alat / sewa','input_manual','hari',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog alat dan mesin.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Alat utama untuk olah tanah.','Catat sebagai sewa, jasa, atau depresiasi alat milik sendiri.','Pastikan biaya operator/BBM jelas termasuk atau terpisah.',''),
('ALT-SPRAYER','Alat & Mesin','Aplikasi Semprot','Sprayer Elektrik','sprayer-elektrik','assets/image/alat_mesin/alat-sprayer-elektrik.jpg','padi,jagung,kedelai','Vegetatif / Generatif','alat','input_manual','unit',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog alat dan mesin.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Alat bantu aplikasi pupuk cair atau pestisida.','Untuk alat milik sendiri, catat biaya servis/depresiasi.','Jangan gandakan dengan biaya jasa penyemprotan.',''),
('ALT-COMBINE','Alat & Mesin','Panen','Combine Harvester','combine-harvester','assets/image/alat_mesin/alat-combine-harvester.jpg','padi','Panen','jasa / sewa alat','input_manual','ha',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog alat dan mesin.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memanen padi dengan mesin.','Biasanya dicatat per hektar atau paket panen.','Jangan gandakan dengan tenaga panen manual dan perontokan.',''),
('BHN-KARUNG','Bahan Pendukung','Pengemasan','Karung Panen','karung-panen','assets/image/bahan_pendukung/bahan-karung-panen.jpg','padi,jagung,kedelai','Panen / Pascapanen','bahan habis pakai','jumlah_x_harga','lembar',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog bahan pendukung/pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Wadah pengemasan hasil panen.','Isi harga lokal per lembar atau pack.','Pastikan jumlah karung sesuai total hasil.',''),
('BHN-TERPAL','Bahan Pendukung','Pengeringan','Terpal Jemur','terpal-jemur','assets/image/bahan_pendukung/bahan-terpal-jemur.jpg','padi,jagung,kedelai','Pascapanen','aset ringan','input_manual','unit',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Alas penjemuran hasil panen.','Bisa dicatat sebagai beli atau biaya pakai musim ini.','Jangan masukkan harga penuh tiap musim jika terpal dipakai berulang.',''),
('PAN-PADI','Panen','Jasa Panen','Panen Padi Manual','panen-padi-manual','assets/image/tenaga_kerja/tenaga-panen-padi.jpg','padi','Panen','jasa / tenaga kerja','input_manual','paket',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog panen.','AGROTRACK_KATALOG_PANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Biaya pekerjaan panen padi.','Pisahkan dari pengangkutan dan pascapanen.','Rawan double counting dengan tenaga kerja panen.',''),
('PAN-JAGUNG','Panen','Jasa Panen','Panen Jagung','panen-jagung','assets/image/tenaga_kerja/tenaga-panen-jagung.jpg','jagung','Panen','jasa / tenaga kerja','input_manual','paket',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog panen.','AGROTRACK_KATALOG_PANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Biaya memetik/memanen jagung.','Dapat dicatat borongan atau HOK.','Pisahkan dari pemipilan jika tidak satu paket.',''),
('PAS-JEMUR','Pascapanen','Pengeringan','Jemur / Pengeringan Hasil','jemur-pengeringan-hasil','assets/image/tenaga_kerja/tenaga-jemur-pengeringan.jpg','padi,jagung,kedelai','Pascapanen','jasa / tenaga kerja','input_manual','HOK',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menurunkan kadar air hasil panen.','Bisa memakai tenaga kerja, lantai jemur, atau dryer.','Jangan dobel dengan jasa pascapanen paket.',''),
('PAS-PIPIL-JAGUNG','Pascapanen','Pemipilan','Pemipilan Jagung','pemipilan-jagung','assets/image/alat_mesin/alat-corn-sheller.jpg','jagung','Pascapanen','jasa / alat','input_manual','kg',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memisahkan biji jagung dari tongkol.','Pisahkan dari biaya panen jika tidak satu paket.','Jagung terlalu basah meningkatkan kerusakan biji.',''),
('TRN-PICKUP','Transportasi & Logistik','Angkut Hasil','Pickup Hasil Panen','pickup-hasil-panen','assets/image/transportasi/transport-pickup-hasil-panen.jpg','padi,jagung,kedelai','Panen / Pascapanen','transportasi','input_manual','rit',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog transportasi dan logistik.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengangkut hasil panen dari lahan ke gudang/pembeli.','Catat per rit, km, atau paket sesuai lokal.','Jangan gandakan dengan ongkos pembeli jika sudah ditanggung pembeli.',''),
('TRN-BONGKAR','Transportasi & Logistik','Bongkar Muat','Bongkar Muat Hasil','bongkar-muat-hasil','assets/image/transportasi/transport-bongkar-muat.jpg','padi,jagung,kedelai','Panen / Pascapanen','tenaga kerja / logistik','input_manual','paket',NULL,NULL,'INPUT_MANUAL_LOKAL','Katalog transportasi dan logistik.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memuat dan menurunkan hasil atau saprodi.','Bisa dicatat terpisah dari kendaraan.','Pastikan tidak masuk dua kali di biaya transport paket.',''),
('MOD-KAS-AWAL','Modal & Administrasi','Sumber Modal','Modal Sendiri / Kas Awal','modal-sendiri-kas-awal',NULL,'padi,jagung,kedelai','Pra-tanam','cash-in','input_modal','rupiah',NULL,NULL,'INPUT_MANUAL','Dokumen modal menyebut modal bukan biaya produksi langsung.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat dana pribadi yang dipakai memulai musim.','Tidak masuk biaya produksi langsung kecuali ada biaya peluang yang dipilih.','Jangan dihitung sebagai biaya operasional agar profit tidak salah.',''),
('MOD-KUR','Modal & Administrasi','Sumber Modal Formal','Pinjaman KUR / Bank','pinjaman-kur-bank',NULL,'padi,jagung,kedelai','Pra-tanam','cash-in + kewajiban','pokok_bunga_tenor','rupiah',NULL,NULL,'INPUT_MANUAL_REFERENSI_KUR','KUR/BRI/OJK sebagai referensi konsep, angka wajib editable.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat sumber modal dari bank atau KUR.','Pokok pinjaman adalah kewajiban, bukan biaya produksi.','Hanya bunga/admin yang bisa menjadi biaya jika dicatat terpisah.',''),
('MOD-IURAN','Modal & Administrasi','Administrasi','Iuran Kelompok Tani','iuran-kelompok-tani',NULL,'padi,jagung,kedelai','Pra-tanam / Selama musim','administrasi','input_manual','rupiah',NULL,NULL,'INPUT_MANUAL','Dokumen modal dan administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat iuran sosial/kelompok yang relevan dengan musim.','Masukkan sebagai biaya hanya jika benar dibayar untuk musim ini.','Jangan gabungkan dengan modal pokok.',''),
('RSK-GAGAL-PANEN','Risiko / Kerugian','Produksi','Risiko Gagal Panen','risiko-gagal-panen',NULL,'padi,jagung,kedelai','Semua fase','risiko','catatan_risiko','rupiah',NULL,NULL,'INPUT_MANUAL','Katalog risiko/kerugian menekankan pencatatan estimasi dampak.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat potensi kerugian karena gagal panen.','Dipakai sebagai risk register, bukan biaya otomatis.','Kerugian baru memengaruhi analisis jika benar terjadi dan dicatat.',''),
('RSK-SUSUT-PASCAPANEN','Risiko / Kerugian','Pascapanen','Susut / Kehilangan Pascapanen','susut-kehilangan-pascapanen',NULL,'padi,jagung,kedelai','Pascapanen','risiko / pengurang hasil','catatan_risiko','rupiah',NULL,NULL,'INPUT_MANUAL','Katalog pascapanen dan risiko.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat susut hasil saat pengeringan, sortasi, atau penyimpanan.','Dapat dicatat sebagai risiko atau pengurang hasil.','Jangan otomatis dihitung biaya tanpa input nilai aktual.','')
ON DUPLICATE KEY UPDATE
  kategori=VALUES(kategori),
  subkategori=VALUES(subkategori),
  nama=VALUES(nama),
  image_path=VALUES(image_path),
  komoditas=VALUES(komoditas),
  fase=VALUES(fase),
  jenis_biaya=VALUES(jenis_biaya),
  mode_biaya=VALUES(mode_biaya),
  satuan_default=VALUES(satuan_default),
  harga_min=VALUES(harga_min),
  harga_max=VALUES(harga_max),
  harga_status=VALUES(harga_status),
  sumber_referensi=VALUES(sumber_referensi),
  sumber_dokumen=VALUES(sumber_dokumen),
  tanggal_cek_harga=VALUES(tanggal_cek_harga),
  fungsi=VALUES(fungsi),
  keterangan=VALUES(keterangan),
  risiko=VALUES(risiko),
  admin_note=VALUES(admin_note),
  is_active=1;

UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-moluskisida.jpg' WHERE kode = 'LIN-MOLUSKISIDA';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-rodentisida.jpg' WHERE kode = 'LIN-RODENTISIDA';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-nematisida.jpg' WHERE kode = 'LIN-NEMATISIDA';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-akarisida.jpg' WHERE kode = 'LIN-AKARISIDA';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-perekat-perata.jpg' WHERE kode = 'LIN-PEREKAT';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-beauveria.jpg' WHERE kode = 'LIN-BEAUVERIA';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-metarhizium.jpg' WHERE kode = 'LIN-METARHIZIUM';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-perangkap-feromon.jpg' WHERE kode = 'LIN-PERANGKAP-FEROMON';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-yellow-sticky-trap.jpg' WHERE kode = 'LIN-YELLOW-STICKY-TRAP';
UPDATE katalog_items SET image_path = 'assets/image/perlindungan_tanaman/perlintan-perangkap-tikus.jpg' WHERE kode = 'LIN-PERANGKAP-TIKUS';
UPDATE katalog_items SET image_path = 'assets/image/tenaga_kerja/tenaga-angkut-hasil.jpg' WHERE kode = 'PAN-ANGKUT';
UPDATE katalog_items SET image_path = 'assets/image/bahan_pendukung/bahan-jaring-padi.jpg' WHERE kode = 'PAN-JARING';
UPDATE katalog_items SET image_path = 'assets/image/bahan_pendukung/bahan-karung-panen.jpg' WHERE kode = 'PAN-KARUNG';
UPDATE katalog_items SET image_path = 'assets/image/tenaga_kerja/tenaga-panen-kedelai.jpg' WHERE kode = 'PAN-KEDELAI';
UPDATE katalog_items SET image_path = 'assets/image/bahan_pendukung/bahan-tali-rafia.jpg' WHERE kode = 'PAN-TALI';
UPDATE katalog_items SET image_path = 'assets/image/alat_mesin/alat-timbangan-digital.jpg' WHERE kode = 'PAN-TIMBANG';
UPDATE katalog_items SET image_path = 'assets/image/bahan_pendukung/bahan-karung-panen.jpg' WHERE kode = 'PAS-KARUNG';
UPDATE katalog_items SET image_path = 'assets/image/alat_mesin/alat-power-thresher.jpg' WHERE kode = 'PAS-RONTOK';
UPDATE katalog_items SET image_path = 'assets/image/transportasi/transport-gudang-penyimpanan.jpg' WHERE kode = 'PAS-SIMPAN';
UPDATE katalog_items SET image_path = 'assets/image/tenaga_kerja/tenaga-jemur-pengeringan.jpg' WHERE kode = 'PAS-SORTASI';
UPDATE katalog_items SET image_path = 'assets/image/alat_mesin/alat-timbangan-digital.jpg' WHERE kode = 'PAS-TIMBANG';
