USE agrotrack;

DELETE FROM katalog_items WHERE kode = 'ALT-SPRAYER-MANUAL';

INSERT INTO katalog_items
(kode, kategori, subkategori, nama, slug, image_path, komoditas, fase, jenis_biaya, mode_biaya, satuan_default, harga_min, harga_max, harga_status, sumber_referensi, sumber_dokumen, tanggal_cek_harga, fungsi, keterangan, risiko, admin_note, detail_json, is_active)
VALUES
('ALT-SPRAYER','Alat & Mesin','Alat Semprot','Sprayer Manual / Knapsack Sprayer','alat-sprayer-manual','assets/image/alat_mesin/alat-sprayer-manual.jpg','padi,jagung,kedelai','Vegetatif / Generatif','alat','beli_baru','unit',165000,666000,'TERVERIFIKASI_MARKETPLACE','Lazada sprayer 16 liter; Shopee sprayer manual 16 L; Chainsaw Surabaya Tasco TB16 SNI.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menyemprot pestisida, pupuk cair, POC, atau agens hayati secara manual.','Murah, ringan, mudah dirawat, dan tidak membutuhkan baterai.','Membutuhkan tenaga pompa manual; kurang efisien untuk lahan luas.','Biaya alat dipisahkan dari bahan semprot dan tenaga penyemprotan.',JSON_OBJECT('nama_ui','Sprayer Manual / Knapsack Sprayer','nama_file','alat-sprayer-manual.jpg','kategori','Alat & Mesin','subkategori','Alat semprot','fase_penggunaan',JSON_ARRAY('Vegetatif','Generatif','Perlindungan tanaman','Pemupukan cair'),'relevan_untuk',JSON_ARRAY('Padi','Jagung','Kedelai'),'overlap_dengan',JSON_ARRAY('Perlindungan Tanaman','Tenaga Penyemprotan'),'mode_biaya',JSON_ARRAY('beli_baru','milik_sendiri','pinjam_kelompok','biaya_servis_sparepart'),'harga_referensi','Lazada 16 L sekitar Rp165.000-Rp175.229; Shopee 16 L Rp190.000; Chainsaw Surabaya/Tasco 16 L Rp600.000-Rp666.000.','status_harga','TERVERIFIKASI_MARKETPLACE','fungsi','Menyemprot pestisida, pupuk cair, POC, atau agens hayati secara manual.','keunggulan','Murah, ringan, mudah dirawat, tidak butuh baterai.','keterbatasan','Membutuhkan tenaga pompa manual; kurang efisien untuk lahan luas.','catatan_k3','Untuk pestisida, wajib APD dan mengikuti label produk.'),1),
('ALT-SPRAYER-ELEKTRIK','Alat & Mesin','Alat Semprot Elektrik','Sprayer Elektrik','alat-sprayer-elektrik','assets/image/alat_mesin/alat-sprayer-elektrik.jpg','padi,jagung,kedelai','Vegetatif / Generatif','alat','beli_baru','unit',228888,1213000,'TERVERIFIKASI_MARKETPLACE','Shopee sprayer elektrik 16 L; Lazada sprayer elektrik 16 L; Blibli sprayer elektrik 16 L.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Penyemprotan dengan bantuan baterai atau pompa elektrik.','Lebih ringan operasionalnya dibanding manual dan tekanan semprot lebih stabil.','Perlu baterai, charger, serta perawatan pompa.','Tetap pisahkan biaya alat dari bahan semprot dan tenaga operator.',JSON_OBJECT('nama_ui','Sprayer Elektrik','nama_file','alat-sprayer-elektrik.jpg','kategori','Alat & Mesin','subkategori','Alat semprot elektrik','fase_penggunaan',JSON_ARRAY('Vegetatif','Generatif','Perlindungan tanaman','Pemupukan cair'),'relevan_untuk',JSON_ARRAY('Padi','Jagung','Kedelai'),'overlap_dengan',JSON_ARRAY('Perlindungan Tanaman','Tenaga Penyemprotan'),'mode_biaya',JSON_ARRAY('beli_baru','milik_sendiri','pinjam_kelompok','biaya_servis_sparepart'),'harga_referensi','Shopee, Lazada, dan Blibli untuk sprayer elektrik 16 L sekitar Rp228.888-Rp1.213.000.','status_harga','TERVERIFIKASI_MARKETPLACE','fungsi','Penyemprotan dengan bantuan baterai/pompa elektrik.','keunggulan','Lebih ringan operasionalnya dibanding manual, tekanan semprot lebih stabil.','keterbatasan','Perlu baterai/charger, risiko kerusakan pompa atau baterai.'),1),
('ALT-POMPA-AIR','Alat & Mesin','Mesin Irigasi','Pompa Air Pertanian / Alkon','alat-pompa-air','assets/image/alat_mesin/alat-pompa-air.jpg','padi,jagung,kedelai','Pra-tanam / Vegetatif / Generatif','alat','beli_baru_disusutkan','unit',1275000,7347750,'TERVERIFIKASI_MARKETPLACE','Shopee, Lazada, PaDi UMKM, Blibli.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengalirkan air dari sumber ke lahan.','Penting saat kemarau atau irigasi tidak cukup.','Perlu BBM/listrik, operator, selang/pipa, dan servis.','Overlap dengan Air & Irigasi.',JSON_OBJECT('nama_ui','Pompa Air Pertanian / Alkon','nama_file','alat-pompa-air.jpg','kategori','Alat & Mesin','subkategori','Mesin irigasi','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','sewa_harian','milik_sendiri','pinjam_kelompok','biaya_bbm_listrik','biaya_operator'),'fungsi','Mengalirkan air dari sumber air ke lahan.','catatan_overlap','Overlap dengan Air & Irigasi.'),1),
('ALT-TRAKTOR','Alat & Mesin','Mesin Olah Tanah','Traktor Roda Dua / Hand Tractor','alat-traktor-roda-dua','assets/image/alat_mesin/alat-traktor-roda-dua.jpg','padi,jagung,kedelai','Pra-tanam','alat','jasa_per_ha','unit',15072000,60528000,'TERVERIFIKASI_MARKETPLACE','Quick, Blibli, Indotrading, Inaproc, Antara Foto.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengolah tanah sebelum tanam.','Default biaya petani lebih realistis sebagai jasa per hektar, bukan otomatis harga beli.','Harga beli tinggi; butuh operator, BBM, servis, dan perawatan.','Jika jasa olah tanah sudah dicatat di Persiapan Lahan, jangan catat biaya traktor lagi kecuali beli/sewa alat terpisah.',JSON_OBJECT('nama_ui','Traktor Roda Dua / Hand Tractor','nama_file','alat-traktor-roda-dua.jpg','kategori','Alat & Mesin','subkategori','Mesin olah tanah','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','jasa_per_ha','sewa_harian','milik_sendiri','pinjam_kelompok','biaya_operator','biaya_bbm_listrik'),'harga_referensi','Quick traktor roda dua sekitar Rp15.072.000-Rp60.528.000; jasa olah tanah dalam beberapa sumber sekitar Rp900.000-Rp2.000.000/ha.','fungsi','Mengolah tanah sebelum tanam.','catatan_overlap','Overlap dengan Persiapan Lahan.'),1),
('ALT-ROTAVATOR','Alat & Mesin','Mesin/Attachment Olah Tanah','Rotavator / Bajak Rotary','alat-rotavator','assets/image/alat_mesin/alat-rotavator.jpg','padi,jagung,kedelai','Pra-tanam','alat','jasa_per_ha','unit',1215000,47928000,'TERVERIFIKASI_MARKETPLACE','Quick, Lazada, Shopee.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menggemburkan dan meratakan tanah.','Sering sudah termasuk paket jasa olah tanah.','Tidak selalu perlu jika jasa olah tanah sudah lengkap.','Overlap dengan Persiapan Lahan.',JSON_OBJECT('nama_ui','Rotavator / Bajak Rotary','nama_file','alat-rotavator.jpg','kategori','Alat & Mesin','subkategori','Mesin/attachment olah tanah','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','jasa_per_ha','sewa_harian','milik_sendiri','biaya_operator','biaya_bbm_listrik'),'fungsi','Menggemburkan dan meratakan tanah.','catatan_overlap','Overlap dengan Persiapan Lahan.'),1),
('ALT-RICE-TRANSPLANTER','Alat & Mesin','Mesin Tanam Padi','Rice Transplanter','alat-rice-transplanter','assets/image/alat_mesin/alat-rice-transplanter.jpg','padi','Tanam','alat','jasa_per_ha','unit',61373000,69064200,'TERVERIFIKASI_MARKETPLACE','Indotara Persada, Blibli.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menanam bibit padi secara mekanis.','Lebih cepat, rapi, dan efisien.','Butuh bibit/persemaian khusus dan kondisi sawah mendukung.','Overlap dengan Tenaga Tanam Padi.',JSON_OBJECT('nama_ui','Rice Transplanter','nama_file','alat-rice-transplanter.jpg','kategori','Alat & Mesin','subkategori','Mesin tanam padi','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','jasa_per_ha','sewa_harian','milik_sendiri','pinjam_kelompok','biaya_operator','biaya_bbm_listrik'),'fungsi','Menanam bibit padi secara mekanis.','catatan_overlap','Alternatif tenaga tanam manual.'),1),
('ALT-COMBINE','Alat & Mesin','Mesin Panen','Combine Harvester Padi','alat-combine-harvester','assets/image/alat_mesin/alat-combine-harvester.jpg','padi','Panen','alat','jasa_per_ha','unit',149047200,543790800,'TERVERIFIKASI_CAMPURAN','Blibli, Kubota, iHarvester, Yanmar/Andaro.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memanen padi secara mekanis, biasanya mencakup potong, rontok, dan pembersihan awal.','Untuk petani kecil lebih realistis dicatat sebagai jasa panen per hektar atau per petak.','Harga beli sangat tinggi, butuh operator, kondisi lahan mendukung, dan perawatan tinggi.','Jika panen pakai combine, biaya tenaga panen manual dan power thresher biasanya tidak perlu dicatat penuh.',JSON_OBJECT('nama_ui','Combine Harvester Padi','nama_file','alat-combine-harvester.jpg','kategori','Alat & Mesin','subkategori','Mesin panen','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','jasa_per_ha','jasa_per_petak','milik_sendiri','pinjam_kelompok','biaya_operator','biaya_bbm_listrik'),'harga_referensi','Blibli mini rice harvester Temco 4RM-1.1 Rp149.047.200; combine Temco 4CH-4.0 Rp527.385.000; Temco 4CH-6.0 Rp543.790.800; Kubota umum sekitar Rp200.000.000-Rp600.000.000 dalam sumber pasar.','fungsi','Memanen padi secara mekanis.','catatan_overlap','Overlap dengan Panen, Tenaga Panen Padi, dan Power Thresher.'),1),
('ALT-POWER-THRESHER','Alat & Mesin','Mesin Pascapanen','Power Thresher / Mesin Perontok','alat-power-thresher','assets/image/alat_mesin/alat-power-thresher.jpg','padi,kedelai','Panen / Pascapanen','alat','jasa_per_hasil','unit',4619000,16095000,'TERVERIFIKASI_MARKETPLACE','Shopee, Indotrading, Maksindo, Changdong.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Merontokkan gabah atau biji dari tanaman setelah panen.','Butuh operator, bahan bakar/listrik, dan perawatan.','Tidak perlu jika combine sudah mencakup perontokan.','Overlap dengan Tenaga Panen dan Pascapanen.',JSON_OBJECT('nama_ui','Power Thresher / Mesin Perontok','nama_file','alat-power-thresher.jpg','kategori','Alat & Mesin','subkategori','Mesin pascapanen/perontok','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','sewa_harian','jasa_per_hasil','milik_sendiri','biaya_operator','biaya_bbm_listrik'),'fungsi','Merontokkan gabah/padi atau biji dari tanaman setelah panen.','catatan_overlap','Tidak perlu jika combine sudah mencakup perontokan.'),1),
('ALT-CORN-SHELLER','Alat & Mesin','Mesin Pascapanen Jagung','Corn Sheller / Mesin Pemipil Jagung','alat-corn-sheller','assets/image/alat_mesin/alat-corn-sheller.jpg','jagung','Pascapanen','alat','jasa_per_hasil','unit',2094560,23000000,'TERVERIFIKASI_MARKETPLACE','Kubota, Blibli, Changdong, Kencana Jaya, Indotrading.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memipil biji jagung dari tongkol.','Butuh operator dan kondisi jagung sesuai.','Biaya mesin tidak perlu bila cukup bayar jasa pemipilan.','Overlap dengan pascapanen jagung dan tenaga pemipilan.',JSON_OBJECT('nama_ui','Corn Sheller / Mesin Pemipil Jagung','nama_file','alat-corn-sheller.jpg','kategori','Alat & Mesin','subkategori','Mesin pascapanen jagung','mode_biaya',JSON_ARRAY('beli_baru','beli_baru_disusutkan','sewa_harian','jasa_per_hasil','milik_sendiri','biaya_operator','biaya_bbm_listrik'),'fungsi','Memipil jagung dari tongkol.','catatan_overlap','Overlap dengan pascapanen jagung dan tenaga pemipilan.'),1),
('ALT-TIMBANGAN-DIGITAL','Alat & Mesin','Alat Ukur','Timbangan Digital Pertanian','alat-timbangan-digital','assets/image/alat_mesin/alat-timbangan-digital.jpg','padi,jagung,kedelai','Panen / Pascapanen','alat','beli_baru','unit',489500,3020000,'TERVERIFIKASI_MARKETPLACE','Shopee, Lazada, Monotaro, RupaRupa.','AGROTRACK_KATALOG_ALAT_MESIN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menimbang hasil panen, karung, input, atau penjualan.','Perlu kapasitas dan akurasi sesuai kebutuhan.','Biaya alat hanya jika dibeli/disewa.','Overlap dengan panen, pascapanen, dan laporan.',JSON_OBJECT('nama_ui','Timbangan Digital Pertanian','nama_file','alat-timbangan-digital.jpg','kategori','Alat & Mesin','subkategori','Alat ukur hasil/input','mode_biaya',JSON_ARRAY('beli_baru','milik_sendiri','pinjam_kelompok','biaya_servis_sparepart'),'fungsi','Menimbang hasil panen dan input pertanian.','catatan_overlap','Overlap dengan panen, pascapanen, dan laporan.'),1)
ON DUPLICATE KEY UPDATE
  kategori = VALUES(kategori),
  subkategori = VALUES(subkategori),
  nama = VALUES(nama),
  slug = VALUES(slug),
  image_path = VALUES(image_path),
  komoditas = VALUES(komoditas),
  fase = VALUES(fase),
  jenis_biaya = VALUES(jenis_biaya),
  mode_biaya = VALUES(mode_biaya),
  satuan_default = VALUES(satuan_default),
  harga_min = VALUES(harga_min),
  harga_max = VALUES(harga_max),
  harga_status = VALUES(harga_status),
  sumber_referensi = VALUES(sumber_referensi),
  sumber_dokumen = VALUES(sumber_dokumen),
  tanggal_cek_harga = VALUES(tanggal_cek_harga),
  fungsi = VALUES(fungsi),
  keterangan = VALUES(keterangan),
  risiko = VALUES(risiko),
  admin_note = VALUES(admin_note),
  detail_json = VALUES(detail_json),
  is_active = VALUES(is_active);

