USE agrotrack;
INSERT IGNORE INTO katalog_items
(kode,kategori,subkategori,nama,slug,image_path,komoditas,fase,jenis_biaya,mode_biaya,satuan_default,harga_min,harga_max,harga_status,sumber_referensi,sumber_dokumen,tanggal_cek_harga,fungsi,keterangan,risiko,admin_note,detail_json,is_active)
VALUES
('PAS-JEMUR','Pascapanen','Pengeringan Hasil','Jemur / Pengeringan Hasil','jemur-pengeringan-hasil','assets/image/pascapanen/tenaga-jemur-pengeringan.jpg','padi,jagung,kedelai','Pascapanen','tenaga_kerja','hok','HOK',50000,250000,'INPUT_MANUAL_LOKAL','MD Pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menurunkan kadar air hasil agar aman disimpan/dijual.','Biaya bisa berupa tenaga jemur, terpal, atau sewa tempat.','Hujan, jamur, kadar air tidak seragam.','Hubungkan dengan terpal dan target kadar air.','{}',1),
('PAS-PIPIL-JAGUNG','Pascapanen','Pemipilan Jagung','Pemipilan Jagung','pemipilan-jagung','assets/image/pascapanen/alat-corn-sheller.jpg','jagung','Pascapanen','alat','jasa_per_kg','kg',100,1500,'INPUT_MANUAL_LOKAL','MD Pascapanen dan alat mesin.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memisahkan biji jagung dari tongkol.','Biaya realistis per kg, karung, atau jasa mesin.','Jagung terlalu basah meningkatkan kerusakan.','Pisahkan dari biaya panen jagung.','{}',1),
('PAS-RONTOK','Pascapanen','Perontokan Padi/Kedelai','Perontokan Padi/Kedelai','perontokan-padi-kedelai','assets/image/pascapanen/alat-power-thresher.jpg','padi,kedelai','Pascapanen','alat','jasa_per_hasil','unit',5000,200000,'TERVERIFIKASI_MARKETPLACE','MD Pascapanen dan alat mesin.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memisahkan gabah atau biji dari tanaman/brangkasan.','Biji bisa pecah jika terlalu kering atau mesin tak sesuai.','Jika combine sudah dipakai, perontokan bisa ikut paket.','Overlap dengan combine dan tenaga panen.','{}',1),
('PAS-SORTASI','Pascapanen','Sortasi dan Pembersihan','Sortasi dan Pembersihan','sortasi-dan-pembersihan','assets/image/pascapanen/tenaga-jemur-pengeringan.jpg','padi,jagung,kedelai','Pascapanen','tenaga_kerja','hok','HOK',50000,250000,'INPUT_MANUAL_LOKAL','MD Pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Memisahkan kotoran, biji rusak, dan material asing.','Mutu turun jika kotoran tinggi.','Penting untuk jagung dan kedelai biji.','Kualitas hasil bisa dipakai untuk harga jual.','{}',1),
('PAS-TIMBANG','Pascapanen','Penimbangan Hasil','Penimbangan Hasil','penimbangan-hasil','assets/image/pascapanen/alat-timbangan-digital.jpg','padi,jagung,kedelai','Pascapanen','alat','beli_baru','unit',489500,3020000,'TERVERIFIKASI_MARKETPLACE','MD Pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengukur hasil aktual untuk laporan dan pendapatan.','Data tidak akurat jika hanya pakai estimasi karung.','Harus terhubung ke hasil panen.','Overlap dengan panen dan laporan.','{}',1),
('PAS-KARUNG','Pascapanen','Pengemasan Karung','Pengemasan Karung','pengemasan-karung','assets/image/pascapanen/bahan-karung-panen.jpg','padi,jagung,kedelai','Pascapanen','bahan','beli_ulang','karung',3500,8500,'TERVERIFIKASI_MARKETPLACE','MD Pascapanen dan bahan pendukung.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menyiapkan hasil agar mudah disimpan/diangkut/dijual.','Karung buruk mudah robek atau kotor.','Biaya karung dan tenaga kemas dipisah.','Gunakan bersama tali rafia.','{}',1),
('PAS-SIMPAN','Pascapanen','Penyimpanan Sementara','Penyimpanan Sementara','penyimpanan-sementara','assets/image/pascapanen/transport-gudang-penyimpanan.jpg','padi,jagung,kedelai','Pascapanen','administrasi','sewa','hari',10000,250000,'INPUT_MANUAL_LOKAL','MD Pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menyimpan hasil sementara sebelum dijual atau diproses.','Risiko lembap, jamur, dan hama gudang.','Biaya gudang/iuran perlu dipisah.','Hubungkan dengan kadar air akhir.','{}',1),
('PAS-SUSUT','Pascapanen','Susut / Kehilangan Pascapanen','Susut / Kehilangan Pascapanen','susut-kehilangan-pascapanen','assets/image/pascapanen/default.jpg','padi,jagung,kedelai','Pascapanen','risiko','input_manual','persen',0,0,'INPUT_MANUAL','MD Pascapanen.','AGROTRACK_KATALOG_PASCAPANEN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat kehilangan hasil saat jemur, simpan, atau proses pascapanen.','Berjamur, pecah, dan dimakan hama.','Tidak wajib asset.','Munculkan sebagai pengurang hasil.','{}',1);

