USE agrotrack;
INSERT IGNORE INTO katalog_items
(kode,kategori,subkategori,nama,slug,image_path,komoditas,fase,jenis_biaya,mode_biaya,satuan_default,harga_min,harga_max,harga_status,sumber_referensi,sumber_dokumen,tanggal_cek_harga,fungsi,keterangan,risiko,admin_note,detail_json,is_active)
VALUES
('TRN-PICKUP','Transportasi & Logistik','Pickup Hasil Panen','Pickup Hasil Panen','pickup-hasil-panen','assets/image/transportasi/transport-pickup-hasil-panen.jpg','padi,jagung,kedelai','Panen/Penjualan','transport','sewa_harian','trip',50000,500000,'REFERENSI_JASA_DINAMIS','Deliveree, TheLorry.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengangkut hasil dari lahan ke rumah, gudang, atau pembeli.','Biaya dapat dihitung per trip, km, harian, atau borongan.','Akses jalan sempit, kapasitas terbatas.','Pilih kendaraan sendiri atau sewa/jasa.','{}',1),
('TRN-TOSA','Transportasi & Logistik','Motor Roda Tiga / Tosa','Motor Roda Tiga / Tosa','motor-roda-tiga-tosa','assets/image/transportasi/transport-motor-roda-tiga.jpg','padi,jagung,kedelai','Panen/Penjualan','transport','per_trip','trip',25000,250000,'INPUT_MANUAL_LOKAL','MD Transportasi.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengangkut hasil di akses sempit atau jarak dekat.','Cocok untuk volume kecil dan jalan sempit.','Kapasitas lebih kecil dari pickup.','Pakai untuk trip pendek.','{}',1),
('TRN-GEROBAK','Transportasi & Logistik','Gerobak Dorong / Arco','Gerobak Dorong / Arco','gerobak-dorong-arco','assets/image/transportasi/transport-gerobak-dorong.jpg','padi,jagung,kedelai','Panen/Pascapanen','transport','beli_baru','unit',150000,1500000,'TERVERIFIKASI_MARKETPLACE','Indotrading gerobak sorong.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mengangkut hasil jarak pendek di lahan atau gudang.','Bergantung tenaga manusia.','Kapasitas kecil dan jarak pendek.','Pisahkan alat dan tenaga dorong.','{}',1),
('TRN-GUDANG','Transportasi & Logistik','Gudang Penyimpanan Hasil','Gudang Penyimpanan Hasil','gudang-penyimpanan-hasil','assets/image/transportasi/transport-gudang-penyimpanan.jpg','padi,jagung,kedelai','Pascapanen/Penjualan','sewa','sewa_gudang','hari',10000,300000,'INPUT_MANUAL_LOKAL','MD Transportasi dan pascapanen.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Menyimpan hasil sementara sebelum proses atau jual.','Risiko lembap, jamur, dan hama.','Biaya sewa/iuran harus jelas.','Hubungkan dengan kadar air dan masa simpan.','{}',1),
('TRN-BONGKAR','Transportasi & Logistik','Bongkar Muat Hasil Panen','Bongkar Muat Hasil Panen','bongkar-muat-hasil-panen','assets/image/transportasi/transport-bongkar-muat.jpg','padi,jagung,kedelai','Panen/Penjualan','tenaga_kerja','borongan','karung',2500,20000,'INPUT_MANUAL_LOKAL','MD Transportasi.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Loading dan unloading karung/hasil panen.','Biaya bisa per karung, per trip, atau borongan.','Jangan digabung otomatis dengan kendaraan.','Bisa satu paket atau terpisah.','{}',1),
('TRN-ANGKUT','Transportasi & Logistik','Tenaga Angkut Hasil','Tenaga Angkut Hasil','tenaga-angkut-hasil','assets/image/transportasi/tenaga-angkut-hasil.jpg','padi,jagung,kedelai','Panen/Pascapanen','tenaga_kerja','per_trip','trip',25000,150000,'INPUT_MANUAL_LOKAL','MD Transportasi dan panen.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Angkut manual antartitik pada lahan atau gudang.','Biaya sering per karung atau per trip.','Bergantung tenaga kerja lokal.','Tidak sama dengan ongkir kendaraan.','{}',1),
('TRN-TIMBANG','Transportasi & Logistik','Timbang & Serah Terima','Timbang & Serah Terima','timbang-serah-terima','assets/image/transportasi/alat-timbangan-digital.jpg','padi,jagung,kedelai','Penjualan','alat','jasa_timbang','kg',100,5000,'TERVERIFIKASI_MARKETPLACE','MD Transportasi.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Validasi bobot saat transaksi/logistik.','Biaya hanya jika alat/jasa timbang dipakai.','Tidak digabung dengan ongkos angkut.','Terhubung ke hasil dan penjualan.','{}',1),
('TRN-BBM','Transportasi & Logistik','Biaya BBM/Operasional Kendaraan','Biaya BBM/Operasional Kendaraan','bbm-operasional-kendaraan','assets/image/transportasi/bahan-jerigen.jpg','padi,jagung,kedelai','Panen/Penjualan','bahan','input_manual','liter',0,0,'HARGA_BBM_DINAMIS','MD Transportasi.','AGROTRACK_KATALOG_TRANSPORTASI_LOGISTIK_PADI_JAGUNG_KEDELAI.md','2026-06-16','Biaya bahan bakar kendaraan/pompa logistik.','Sangat tergantung jarak dan kendaraan.','Harga BBM harus editable.','Gunakan untuk trip dan operasional.','{}',1);

