USE agrotrack;
INSERT IGNORE INTO katalog_items
(kode,kategori,subkategori,nama,slug,image_path,komoditas,fase,jenis_biaya,mode_biaya,satuan_default,harga_min,harga_max,harga_status,sumber_referensi,sumber_dokumen,tanggal_cek_harga,fungsi,keterangan,risiko,admin_note,detail_json,is_active)
VALUES
('MOD-KAS-AWAL','Modal & Administrasi','Modal Sendiri','Modal Sendiri / Kas Awal','modal-sendiri-kas-awal','assets/image/modal/modal-kas-usahatani.svg','padi,jagung,kedelai','Pra-tanam','modal','input_modal_sendiri','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi, BPS, KUR BRI, OJK.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat dana pribadi yang dipakai memulai musim tanam.','Bukan biaya produksi langsung, tetapi sumber dana.','Jangan otomatis mengurangi profit sebagai biaya.','Modal = sumber dana, bukan biaya.','{}',1),
('MOD-KUR','Modal & Administrasi','Pinjaman KUR / Bank','Pinjaman KUR / Bank','pinjaman-kur-bank','assets/image/modal/modal-pinjaman-bank.svg','padi,jagung,kedelai','Pra-tanam/Selama musim','modal','pokok_pinjaman','rupiah',0,0,'INPUT_MANUAL','KUR, OJK, Ekon.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat sumber modal dari bank/lembaga formal.','Pokok kewajiban; bunga/admin menjadi biaya pembiayaan.','Suku bunga dan tenor harus editable.','Pisahkan pokok dan biaya pembiayaan.','{}',1),
('MOD-IURAN','Modal & Administrasi','Iuran Kelompok Tani','Iuran Kelompok Tani','iuran-kelompok-tani','assets/image/modal/modal-iuran-kelompok.svg','padi,jagung,kedelai','Pra-tanam/Selama musim','administrasi','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat iuran sosial atau kegiatan kelompok tani.','Nominal lokal dan sangat bervariasi.','Tiap kelompok punya aturan sendiri.','Cocok untuk kas kolektif.','{}',1),
('MOD-SEWA-LAHAN','Modal & Administrasi','Sewa Lahan','Sewa Lahan','sewa-lahan','assets/image/modal/modal-sewa-lahan.svg','padi,jagung,kedelai','Pra-tanam/per musim','biaya_tetap','per_musim','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat sewa/bagi hasil lahan.','Bisa per musim, per tahun, atau per ha.','Harus dipisah dari biaya operasional.','Buat jelas sebelum musim dimulai.','{}',1),
('MOD-PBB','Modal & Administrasi','Pajak/Iuran Lahan/PBB','Pajak/Iuran Lahan/PBB','pajak-iuran-lahan-pbb','assets/image/modal/modal-pajak-lahan.svg','padi,jagung,kedelai','Tahunan/musim','administrasi','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat pajak atau iuran lahan periodik.','Bergantung status lahan dan daerah.','Nilai harus editable.','Pisahkan dari sewa lahan.','{}',1),
('MOD-CICILAN-ALAT','Modal & Administrasi','Cicilan Alat/Mesin','Cicilan Alat/Mesin','cicilan-alat-mesin','assets/image/modal/modal-cicilan-alat.svg','padi,jagung,kedelai','Semua fase','pembiayaan_aset','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi dan alat mesin.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat cicilan alat/mesin yang dibeli bertahap.','Bunga dan tenor memengaruhi total biaya.','Aset sebaiknya disusutkan untuk analisis ekonomi.','Pisahkan cicilan pokok dan bunga.','{}',1),
('MOD-BIAYA-ADMIN','Modal & Administrasi','Biaya Administrasi Bank','Biaya Administrasi Bank','biaya-administrasi-bank','assets/image/modal/modal-biaya-admin.svg','padi,jagung,kedelai','Saat transaksi','biaya_transaksi','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Biaya admin, transfer, atau layanan keuangan.','Bergantung lembaga dan produk.','Editable per transaksi.','Jangan gabung dengan pokok pinjaman.','{}',1),
('MOD-CADANGAN','Modal & Administrasi','Dana Cadangan Operasional','Dana Cadangan Operasional','dana-cadangan-operasional','assets/image/modal/modal-cadangan-kas.svg','padi,jagung,kedelai','Semua fase','cadangan','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat dana cadangan untuk kondisi tak terduga.','Biasanya dihitung sebagai persen dari biaya.','Berguna untuk analisis cash flow.','Cadangan bukan biaya operasional langsung.','{}',1),
('MOD-DOKUMEN','Modal & Administrasi','Dokumen dan Pencatatan','Biaya Dokumentasi & Pencatatan','biaya-dokumentasi-pencatatan','assets/image/modal/modal-dokumen.svg','padi,jagung,kedelai','Semua fase','administrasi','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Modal & Administrasi.','AGROTRACK_KATALOG_MODAL_ADMINISTRASI_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat alat tulis, cetak, foto, dan pencatatan.','Nominal kecil tapi sering muncul.','Penting untuk audit dan laporan.','Pisahkan dari biaya produksi fisik.','{}',1);

