USE agrotrack;
INSERT IGNORE INTO katalog_items
(kode,kategori,subkategori,nama,slug,image_path,komoditas,fase,jenis_biaya,mode_biaya,satuan_default,harga_min,harga_max,harga_status,sumber_referensi,sumber_dokumen,tanggal_cek_harga,fungsi,keterangan,risiko,admin_note,detail_json,is_active)
VALUES
('RSK-KEKERINGAN','Risiko / Kerugian','Iklim/Air','Kekeringan','kekeringan','assets/image/risiko/risiko-kekeringan.svg','padi,jagung,kedelai','Semua fase','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian, BPS, Permentan OPT, Jasindo AUTP.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat risiko kekeringan dan dampak tambahannya.','Biaya tambahan irigasi dan nilai hasil hilang.','Biaya pompa naik.','Gunakan untuk risk register dan kerugian aktual.','{}',1),
('RSK-BANJIR','Risiko / Kerugian','Iklim/Air','Banjir / Genangan','banjir-genangan','assets/image/risiko/risiko-banjir.svg','padi,jagung,kedelai','Pra-tanam sampai panen','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat banjir/genangan dan dampaknya.','Tanam ulang, perbaikan, hasil hilang.','Bisa dikurangi dengan drainase.','Kerugian bisa dikurangi klaim asuransi.','{}',1),
('RSK-HAMA','Risiko / Kerugian','OPT','Serangan Hama','serangan-hama','assets/image/risiko/risiko-hama.svg','padi,jagung,kedelai','Vegetatif-generatif','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian, Permentan OPT.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat serangan hama dan biaya pengendalian.','Hasil turun dan biaya naik.','Simpan monitoring OPT.','Jangan dorong semprot berlebihan tanpa monitoring.','{}',1),
('RSK-PENYAKIT','Risiko / Kerugian','OPT','Penyakit Tanaman','penyakit-tanaman','assets/image/risiko/risiko-penyakit.svg','padi,jagung,kedelai','Vegetatif-generatif','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat penyakit tanaman dan dampak finansialnya.','Mutu dan hasil turun.','Catat gejala dan pengendalian.','Terhubung ke perlindungan tanaman.','{}',1),
('RSK-GULMA','Risiko / Kerugian','Kompetisi tanaman','Gulma Tidak Terkendali','gulma-tidak-terkendali','assets/image/risiko/risiko-gulma.svg','padi,jagung,kedelai','Awal-vegetatif','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat kerugian akibat gulma.','Pertumbuhan terganggu dan hasil turun.','Perlu penyiangan tepat waktu.','Hubungkan dengan biaya penyiangan.','{}',1),
('RSK-GAGAL-TUMBUH','Risiko / Kerugian','Produksi','Benih Tidak Tumbuh / Gagal Tumbuh','gagal-tumbuh','assets/image/risiko/risiko-gagal-tumbuh.svg','padi,jagung,kedelai','Tanam-awal','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat benih tidak tumbuh dan biaya penyulaman.','Perlu tanam ulang atau penyulaman.','Pakai cek daya tumbuh.','Kerugian dihitung dari benih tambahan dan hasil hilang.','{}',1),
('RSK-HARGA-TURUN','Risiko / Kerugian','Pasar','Harga Jual Turun','harga-jual-turun','assets/image/risiko/risiko-harga-turun.svg','padi,jagung,kedelai','Panen/penjualan','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat risiko harga jual turun.','Pendapatan turun walau produksi sama.','Simpan harga jual aktual.','Penting untuk analisis profit.','{}',1),
('RSK-INPUT-NAIK','Risiko / Kerugian','Finansial/pasar','Kenaikan Harga Input','kenaikan-harga-input','assets/image/risiko/risiko-input-naik.svg','padi,jagung,kedelai','Pra-tanam/perawatan','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat risiko harga input naik.','Modal membengkak.','Editable per input.','Cocok untuk monitoring biaya musim.','{}',1),
('RSK-ALAT-RUSAK','Risiko / Kerugian','Operasional/aset','Alat/Mesin Rusak','alat-mesin-rusak','assets/image/risiko/risiko-alat-rusak.svg','padi,jagung,kedelai','Semua fase','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat kerusakan alat dan servis.','Pekerjaan tertunda.','Cocok untuk aset dan mesin.','Sambungkan ke modal/cicilan alat.','{}',1),
('RSK-SUSUT-PASCAPANEN','Risiko / Kerugian','Pascapanen','Susut Pascapanen','susut-pascapanen','assets/image/risiko/risiko-susut-pascapanen.svg','padi,jagung,kedelai','Jemur/simpan','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian, Pascapanen.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat susut atau kerusakan hasil setelah panen.','Berjamur, pecah, dimakan hama.','Turunkan dari hasil akhir.','Hubungkan dengan pascapanen dan gudang.','{}',1),
('RSK-KREDIT','Risiko / Kerugian','Finansial','Gagal Bayar Pinjaman','gagal-bayar-pinjaman','assets/image/risiko/risiko-kredit.svg','padi,jagung,kedelai','Akhir musim','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat gagal bayar dan denda.','Utang menumpuk.','Khusus untuk pembiayaan.','Hubungkan dengan modal dan administrasi.','{}',1),
('RSK-KECELAKAAN','Risiko / Kerugian','K3','Kecelakaan Kerja / Paparan Pestisida','kecelakaan-kerja-paparan-pestisida','assets/image/risiko/risiko-kecelakaan-kerja.svg','padi,jagung,kedelai','Penyemprotan/panen','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat kecelakaan kerja dan biaya kesehatan.','Kerja terganggu dan butuh biaya pemulihan.','Wajib catat K3.','Jangan dorong semprot tanpa APD.','{}',1),
('RSK-BENCANA','Risiko / Kerugian','Iklim/bencana','Bencana Alam Ekstrem','bencana-alam-ekstrem','assets/image/risiko/risiko-banjir.svg','padi,jagung,kedelai','Semua fase','risiko','input_manual','rupiah',0,0,'INPUT_MANUAL','MD Risiko / Kerugian.','AGROTRACK_KATALOG_RISIKO_KERUGIAN_PADI_JAGUNG_KEDELAI.md','2026-06-16','Mencatat kejadian bencana besar.','Puso/gagal panen.','Bisa digabung dengan asuransi.','Simpan bukti kejadian.','{}',1);

