<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/core/bootstrap.php'; require_once __DIR__ . '/../../app/core/layout.php'; require_once __DIR__ . '/../../app/core/queries.php';
$user=require_login('petani'); $userId=(int)$user['id']; $summary=petani_summary($userId);
$stmt=db()->prepare('SELECT kategori, SUM(total_biaya) total FROM (SELECT user_id,kategori,total_biaya FROM biaya_produksi UNION ALL SELECT user_id,kategori,total_biaya FROM biaya_operasional) b WHERE user_id=? GROUP BY kategori');$stmt->execute([$userId]);$biaya=$stmt->fetchAll();
$stmt=db()->prepare('SELECT mt.kode_musim, COALESCE(b.biaya,0) biaya, COALESCE(h.pendapatan,0) pendapatan FROM musim_tanam mt LEFT JOIN (SELECT musim_tanam_id, SUM(total_biaya) biaya FROM (SELECT musim_tanam_id,total_biaya FROM biaya_produksi UNION ALL SELECT musim_tanam_id,total_biaya FROM biaya_operasional) biaya_all GROUP BY musim_tanam_id) b ON b.musim_tanam_id=mt.id LEFT JOIN (SELECT musim_tanam_id, SUM(total_pendapatan) pendapatan FROM hasil_panen GROUP BY musim_tanam_id) h ON h.musim_tanam_id=mt.id WHERE mt.user_id=? ORDER BY mt.tanggal_tanam');$stmt->execute([$userId]);$musim=$stmt->fetchAll();
?>
<!doctype html><html lang="id"><head><?php render_head('AgroTrack - Analisis'); ?></head><body data-portal="petani" data-active="analisis" data-base="../../"><?php render_sidebar($user,'analisis');?><main class="app-main"><div class="topbar"><div><h1 class="page-title">Analisis Profit</h1><p class="page-kicker">Grafik biaya, pendapatan, dan profit dari data asli.</p></div><button class="btn btn-primary" id="exportAnalysisPdfBtn" type="button"><span class="material-symbols-outlined">picture_as_pdf</span> Generate PDF</button></div><?php render_page_help('Membaca analisis', ['Cek grafik biaya per kategori untuk melihat pengeluaran terbesar.', 'Bandingkan pendapatan dan biaya per musim.', 'Jika grafik kosong, isi musim tanam, biaya produksi, dan hasil panen dulu.'], 'Analisis ini otomatis berubah mengikuti data yang kamu input.', 'biaya-produksi.php', 'Lengkapi Biaya'); ?>
<section class="row g-3 mb-3"><div class="col-md-4"><div class="stat-card"><div class="stat-label">Total Biaya</div><div class="stat-value"><?=money_id($summary['total_biaya'])?></div></div></div><div class="col-md-4"><div class="stat-card"><div class="stat-label">Pendapatan</div><div class="stat-value"><?=money_id($summary['total_pendapatan'])?></div></div></div><div class="col-md-4"><div class="stat-card"><div class="stat-label">Profit</div><div class="stat-value"><?=money_id($summary['total_profit'])?></div></div></div></section>
<section class="row g-3"><div class="col-xl-4"><div class="panel"><h2 class="section-title">Biaya per Kategori</h2><canvas id="costChart"></canvas></div></div><div class="col-xl-8"><div class="panel"><h2 class="section-title">Pendapatan vs Biaya</h2><canvas id="seasonChart"></canvas></div></div></section>
</main><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js"></script><script src="https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js"></script><script>const biaya=<?=json_encode($biaya,JSON_UNESCAPED_SLASHES)?>;const musim=<?=json_encode($musim,JSON_UNESCAPED_SLASHES)?>;window.agroAnalysisBiaya=biaya;window.agroAnalysisMusim=musim;window.agroAnalysisSummary=<?=json_encode($summary,JSON_UNESCAPED_SLASHES)?>;new Chart(document.getElementById('costChart'),{type:'doughnut',data:{labels:biaya.map(x=>x.kategori),datasets:[{data:biaya.map(x=>Number(x.total)),backgroundColor:['#103f31','#f5a91f','#0f6b4f','#e8f1ff','#c64f4a']}]}});new Chart(document.getElementById('seasonChart'),{type:'bar',data:{labels:musim.map(x=>x.kode_musim),datasets:[{label:'Biaya',data:musim.map(x=>Number(x.biaya)),backgroundColor:'#c64f4a'},{label:'Pendapatan',data:musim.map(x=>Number(x.pendapatan)),backgroundColor:'#0f6b4f'},{label:'Profit',data:musim.map(x=>Number(x.pendapatan)-Number(x.biaya)),backgroundColor:'#f5a91f'}]}});</script><script src="../../assets/js/analisis-petani.js"></script><script src="../../assets/js/app.js"></script></body></html>
