<?php
declare(strict_types=1);
require_once __DIR__ . '/../../app/core/bootstrap.php'; require_once __DIR__ . '/../../app/core/layout.php'; require_once __DIR__ . '/../../app/core/queries.php';
$user=require_login('petani'); $userId=(int)$user['id']; $error=null; $musim=user_musim($userId);
if(request_method()==='POST'){try{verify_csrf();$musimId=post_int('musim_tanam_id');$stmt=db()->prepare('SELECT mt.*, l.luas, t.nama AS tanaman FROM musim_tanam mt JOIN lahan l ON l.id=mt.lahan_id LEFT JOIN tanaman t ON t.id=mt.tanaman_id WHERE mt.id=? AND mt.user_id=?');$stmt->execute([$musimId,$userId]);$m=$stmt->fetch();if(!$m)throw new RuntimeException('Musim tidak valid.');$berat=post_float('berat_kg');$harga=post_float('harga_per_kg');if($berat<=0||$harga<=0)throw new RuntimeException('Hasil dan harga jual harus lebih dari 0.');$total=$berat*$harga;$stmt=db()->prepare('INSERT INTO hasil_panen (user_id,lahan_id,musim_tanam_id,tanggal_panen,komoditas,berat_kg,harga_per_kg,total_pendapatan,kualitas,status,pembeli,catatan) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE tanggal_panen=VALUES(tanggal_panen), berat_kg=VALUES(berat_kg), harga_per_kg=VALUES(harga_per_kg), total_pendapatan=VALUES(total_pendapatan), kualitas=VALUES(kualitas), pembeli=VALUES(pembeli), catatan=VALUES(catatan)');$stmt->execute([$userId,$m['lahan_id'],$musimId,post_string('tanggal_panen',20),$m['tanaman']?:'Panen',$berat,$harga,$total,$_POST['kualitas']??'baik','terverifikasi',post_string('pembeli',120),post_string('catatan',1000)]);flash('success','Hasil panen berhasil disimpan.');redirect_to('hasil-panen.php');}catch(Throwable $e){$error=$e->getMessage();}}
$stmt=db()->prepare('SELECT h.*, mt.kode_musim, (COALESCE((SELECT SUM(total_biaya) FROM biaya_produksi b WHERE b.musim_tanam_id=h.musim_tanam_id),0) + COALESCE((SELECT SUM(total_biaya) FROM biaya_operasional bo WHERE bo.musim_tanam_id=h.musim_tanam_id),0)) AS total_biaya FROM hasil_panen h LEFT JOIN musim_tanam mt ON mt.id=h.musim_tanam_id WHERE h.user_id=? ORDER BY h.tanggal_panen DESC');$stmt->execute([$userId]);$rows=$stmt->fetchAll();
?>
<!doctype html><html lang="id"><head><?php render_head('AgroTrack - Hasil Panen'); ?></head><body data-portal="petani" data-active="panen" data-base="../../"><?php render_sidebar($user,'panen');?><main class="app-main"><div class="topbar"><div><h1 class="page-title">Hasil Panen</h1><p class="page-kicker">Pendapatan dihitung otomatis dari total hasil x harga jual.</p></div></div><?php render_flash();if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php render_page_help('Cara mencatat panen', ['Pilih musim tanam yang sudah selesai atau siap panen.', 'Isi tanggal panen, berat hasil, harga jual, kualitas, dan pembeli.', 'Simpan agar pendapatan dan profit otomatis muncul di analisis.'], 'Satu musim panen akan diperbarui jika kamu menginput ulang musim yang sama.', 'analisis.php', 'Lihat Analisis'); ?>
<section class="row g-3"><div class="col-xl-4"><div class="panel h-100"><h2 class="section-title">Input Panen</h2><form method="post" class="vstack gap-3"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>" /><div><label class="form-label fw-semibold">Musim</label><select class="form-select" name="musim_tanam_id"><?php foreach($musim as $m):?><option value="<?=e($m['id'])?>"><?=e($m['kode_musim'])?> - <?=e($m['tanaman_nama'])?></option><?php endforeach;?></select></div><div><label class="form-label fw-semibold">Tanggal Panen</label><input class="form-control" name="tanggal_panen" type="date" value="<?=e(date('Y-m-d'))?>" /></div><div><label class="form-label fw-semibold">Total Hasil (kg)</label><input class="form-control" name="berat_kg" type="number" step="0.01" min="0.01" required /></div><div><label class="form-label fw-semibold">Harga Jual / kg</label><input class="form-control" name="harga_per_kg" type="number" min="1" required /></div><div><label class="form-label fw-semibold">Kualitas</label><select class="form-select" name="kualitas"><option value="premium">Premium</option><option value="baik" selected>Baik</option><option value="sedang">Sedang</option><option value="rendah">Rendah</option></select></div><div><label class="form-label fw-semibold">Pembeli</label><input class="form-control" name="pembeli" /></div><div><label class="form-label fw-semibold">Catatan</label><textarea class="form-control" name="catatan" rows="3"></textarea></div><button class="btn btn-primary">Simpan Panen</button></form></div></div>
<div class="col-xl-8"><div class="panel"><h2 class="section-title">Riwayat Panen</h2><div class="table-responsive"><table class="table"><thead><tr><th>Tanggal</th><th>Musim</th><th>Komoditas</th><th>Hasil</th><th>Pendapatan</th><th>Profit</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['tanggal_panen'])?></td><td><?=e($r['kode_musim'])?></td><td><?=e($r['komoditas'])?></td><td><?=number_id($r['berat_kg'],2)?> kg</td><td><?=money_id($r['total_pendapatan'])?></td><td><?=money_id((float)$r['total_pendapatan']-(float)$r['total_biaya'])?></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="6" class="text-center text-secondary py-4">Belum ada hasil panen.</td></tr><?php endif;?></tbody></table></div></div></div></section>
</main><script src="../../assets/js/app.js"></script></body></html>
